version: '3'

services:
  app:
    build: .
    container_name: app
    ports:
      - '4000:4000'
    depends_on:
      - mongocontainer
  mongocontainer:
    image: 'mongo:3.6.4'
    container_name: mongocontainer
    ports:
      - '27999:27017'
    volumes:
      - /data/db/yamid/app:/data/db
